name: CI (dev branch)

on:
  push:
    branches: [dev]
  pull_request:
    branches: [dev]

jobs:
  test:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: '3.13'

      - name: Install uv
        run: pip install uv

      - name: Sync dependencies
        run: uv sync --dev

      - name: Run tests
        run: uv run pytest -sv

      - name: Show dynamic version
        run: uv run hatch version

      - name: Build package
        run: uv run hatch build

      - name: Upload build artifact
        uses: actions/upload-artifact@v4
        with:
          name: dev-build
          path: dist/
