name: Release (tagged)

on:
  push:
    tags:
      - 'v*'

jobs:
  release:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: '3.13'

      - name: Install uv
        run: pip install uv

      - name: Sync dependencies
        run: uv sync --dev

      - name: Run tests
        run: uv run pytest -sv

      - name: Show dynamic version
        run: uv run hatch version

      - name: Build package
        run: uv run hatch build

      - name: Upload release artifact
        uses: actions/upload-artifact@v4
        with:
          name: release-build
          path: dist/

      # Optional: create a GitHub Release and upload artifacts
      - name: Create GitHub Release
        uses: softprops/action-gh-release@v2
        with:
          files: dist/*
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
